{
 "title": "Kubernetes Overview",
 "description": "Kubernetes Overview Dashboard highlighting cluster capacity",
 "tags": [
  "kubernetes",
  "lsdcontainer",
  "gke"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n<p style=\"text-align:center;\">LSDobserve - Kubernetes Overview - Version 2.36</p>"
   }
  },
  { "title": "Environment Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Real Time Request CPU on Compute Nodes",
   "type": "gauge",
   "description": "This aggregates all available CPU cores and what is currently allocated. If this graph it's 100% no more pods will be able to start because no more CPU requests are available. We have purposely adjusted this by 112% and not 100% to give you some breathing room.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum ((sum(kube_pod_container_resource_requests_cpu_cores{container!=\"deployment\",container!=\"docker-build\"} > 0) by (container,pod) / count(kube_pod_container_status_running > 0) by (container,pod))*1000)) / (sum (kube_node_status_allocatable_cpu_cores)*1000) * 112"
    }
   ]
  },
  {
   "title": "Real time CPU Usage on Compute Nodes",
   "type": "gauge",
   "description": "This aggregates all available CPU cores and CPU usage of the entire cluster. If this hits 80-100% the entire cluster will suffer from poor performance.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[2m])) / sum (kube_node_status_allocatable_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Total CPU Request of all Project Quotas",
   "type": "gauge",
   "description": "The sum of all the CPU Requests of all the Quotas. This will give you an indication if your cluster is over subscribed with CPU request for all the projects. If all the namespaces were to ask for promised qutoas, and this graph is over 100%, the cluster would not be able to fulfill the request.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"hard\"}) / sum (kube_node_status_allocatable_cpu_cores) *100"
    }
   ]
  },
  {
   "title": "Total Allocatable Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable_cpu_cores)"
    }
   ]
  },
  {
   "title": "Total Used Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum (kube_node_labels)" }
   ]
  },
  { "title": "Alert Status", "type": "alertlist", "gridPos": { "h": 52, "w": 4, "x": 20, "y": 3 } },
  {
   "title": "Real Time Memory Requests on Compute Nodes",
   "type": "gauge",
   "description": "This aggregates all available CPU cores and what is currently allocated. If this graph it's 100% no more pods will be able to start because no more CPU requests are available. We have purposely adjusted this by 112% and not 100% to give you some breathing room.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum ((sum(kube_pod_container_resource_requests_memory_bytes{container!=\"deployment\",container!=\"docker-build\",}))*1000)) / (sum (kube_node_status_capacity_memory_bytes)*1000)  * 100"
    }
   ]
  },
  {
   "title": "Real time Memory  Usage on Compute Nodes",
   "type": "gauge",
   "description": "This aggregates all available Memory on compute nodes and displays Used Memory. Once this hits 100% pods will start dying from Out Of Memory (OOM) errors",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",name!~\"k8s_POD_.*\"}) / sum (kube_node_status_capacity_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Total Memory Request of all Project Quotas",
   "type": "gauge",
   "description": "The sum of all the Memory Requests of all the Quotas. This will give you an indication if your cluster is over subscribed with Memory request for all the projects. If all the namespaces were to ask for promised qutoas, and this graph is over 100%, the cluster would not be able to fulfill the request.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"hard\"}) / sum (kube_node_status_capacity_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_capacity_memory_bytes)"
    }
   ]
  },
  {
   "title": "Total Mem Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",name!~\"k8s_POD_.*\"})"
    }
   ]
  },
  {
   "title": "Pod Limit (20 pods per core)",
   "type": "gauge",
   "description": "The maximum number of pods you can run on the system",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1/((sum(kube_node_status_allocatable_cpu_cores)*20) / (sum(kube_pod_info{created_by_kind!=\"<none>\"}))) * 100 "
    }
   ]
  },
  {
   "title": "CPU Utilization per Node over Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "cpu percentage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (kubernetes_node) (rate( node_cpu_seconds_total {mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{ kubernetes_node }}"
    },
    {}
   ]
  },
  {
   "title": "Memory Usage per Node over Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "memory percentage" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[2m]) + avg_over_time(node_memory_Cached_bytes[2m]) + avg_over_time(node_memory_Buffers_bytes[2m]) + avg_over_time(node_memory_SReclaimable_bytes[2m])) / avg_over_time(node_memory_MemTotal_bytes[2m])))",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "CPU usage per node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent", "label": "CPU" }
   ],
   "targets": [
    {
     "expr": "\nsum by (node) (\n  label_replace(\n    (rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[2m])),\n    \"node\",\"$1\",\"instance\", \"(.+)\"\n  )\n)   \n\n/\n\nsum by (node) (kube_node_status_capacity_cpu_cores)  * 100",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory usage per node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 17 },
   "yaxes": [
    { "format": "percent", "label": "RAM" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (\n  label_replace(\n    container_memory_working_set_bytes{container!=\"\",name!~\"k8s_POD_.*\"},\n    \"node\",\"$1\",\"instance\", \"(.+)\"\n  )\n)\n\n/\n\nsum(kube_node_status_capacity_memory_bytes) by (node) * 100",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Server Load over 15 Minutes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load15", "legendFormat": "{{ kubernetes_node }}" }
   ]
  },
  {
   "title": "Normalised Server Load over 15 Minutes",
   "type": "graph",
   "description": "Percentage total CPUs are overloaded, i.e. the percentage of time processes were waiting for CPU.",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(node_load15) by (kubernetes_node) / sum(kube_node_status_capacity_cpu_cores) by (kubernetes_node)) * 100",
     "legendFormat": "{{kubernetes_node}}"
    },
    {
     "expr": "(100 / sum(kube_node_status_capacity_cpu_cores)by (kubernetes_node)) * (sum(node_load15) by (kubernetes_node) - sum(kube_node_status_capacity_cpu_cores) by (kubernetes_node))",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Per disk utilization > 20% IO",
   "type": "graph",
   "description": "Per disk utilization across all instances",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{device=~\"sd.*\"}[2m]) > 0.20",
     "legendFormat": "{{ kubernetes_node }} - {{ device }}"
    }
   ]
  },
  {
   "title": "Filesystem Utilization for Nodes and PVCs over 70%",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 29 },
   "yaxes": [
    { "format": "percent", "label": "Filesystem Usage" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes {mountpoint!~\".*/host/.*\",mountpoint!~\".*/etc/.*\",mountpoint!~\".*/run/secrets.*\",mountpoint!~\".*/var/run/.*\"} * 100) / node_filesystem_size_bytes {mountpoint!~\".*/host/.*\",mountpoint!~\".*/etc/.*\",mountpoint!~\".*/run/secrets.*\",mountpoint!~\".*/var/run/.*\"}) > 70",
     "legendFormat": "{{ kubernetes_node }} - {{ mountpoint }}"
    },
    {
     "expr": "(kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes) * 100 > 70",
     "legendFormat": "{{ namespace }} - {{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "CPU Usage by Project",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "millicores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[5m])) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Usage by Project",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 35 },
   "yaxes": [
    { "format": "bits", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\",name!~\"k8s_POD_.*\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Dead Prometheus Targets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "up{job=\"kubernetes-nodes\"} != 1",
     "legendFormat": "{{ kubernetes_io_hostname }}"
    },
    {
     "expr": "up{job=\"\"} != 1",
     "legendFormat": "{{ kubernetes_node }}"
    }
   ]
  },
  {
   "title": "Pod with Restarts > 50",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total > 50",
     "legendFormat": "{{ namespace }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "description": "Physical network I/O pressure",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "- sum(rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\"}[2m])) * 8",
     "legendFormat": "<-- RX"
    },
    {
     "expr": "sum(rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\"}[2m])) * 8",
     "legendFormat": "--> TX"
    }
   ]
  },
  {
   "title": "Total time duration the container has been throttled",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "time in seconds" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total[2m]) > 0.1",
     "legendFormat": "{{ namespace }} - {{ pod }}"
    }
   ]
  },
  {
   "title": "Resource Allocation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Largest CPU request/usage disparity per namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short", "label": "cpu cores" }
     ],
     "targets": [
      {
       "expr": "topk(5, (sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)) - (sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[2m])) by (namespace)))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Top 5 Largest Memory request/usage disparity per namespace",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5, (sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)) - (sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\"}) by (namespace)))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "CPU Allocation and Usage on Compute Nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (kube_resourcequota{resource=\"limits.cpu\",type=\"hard\"}) / (sum (machine_cpu_cores{node_role_kubernetes_io_compute!=\"master\",node_role_kubernetes_io_infra!=\"true\"})) * 100 ",
       "legendFormat": "Total CPU Limits Allocated to Projects"
      },
      {
       "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"hard\"}) / (sum (machine_cpu_cores{node_role_kubernetes_io_compute!=\"master\",node_role_kubernetes_io_infra!=\"true\"})) * 100 ",
       "legendFormat": "Total CPU Requests Allocated to Projects"
      },
      {
       "expr": "(sum ((sum(kube_pod_container_resource_limits_cpu_cores{container!=\"deployment\",container!=\"docker-build\",namespace!=\"logging\",namespace!=\"default\",namespace!~\".*openshift-.*\",namespace!~\".*openmonitoring.*\",namespace!~\".*kube-.*\"} > 0) by (container,pod) / count(kube_pod_container_status_running > 0) by (container,pod))*1000)) / (sum (machine_cpu_cores{node_role_kubernetes_io_compute!=\"master\",node_role_kubernetes_io_infra!=\"true\"})*1000)* 112 ",
       "legendFormat": "Total Real Time CPU Limits Allocation"
      },
      {
       "expr": "(sum ((sum(kube_pod_container_resource_requests_cpu_cores{container!=\"deployment\",container!=\"docker-build\",namespace!=\"logging\",namespace!=\"default\",namespace!~\".*openshift-.*\",namespace!~\".*openmonitoring.*\",namespace!~\".*kube-.*\"} > 0) by (container,pod) / count(kube_pod_container_status_running > 0) by (container,pod))*1000)) / (sum (machine_cpu_cores{node_role_kubernetes_io_compute!=\"master\",node_role_kubernetes_io_infra!=\"true\"})*1000) * 112",
       "legendFormat": "Total Real Time CPU Request Allocation"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[2m])) / (sum (machine_cpu_cores{node_role_kubernetes_io_compute!=\"master\",node_role_kubernetes_io_infra!=\"true\"})*1000) * 100",
       "legendFormat": "Total Real Time CPU Usage on Compute"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[2m])) / sum (machine_cpu_cores{node_role_kubernetes_io_master=\"true\"}) * 100",
       "legendFormat": "Total Real Time CPU Usage on Masters"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\"}[2m])) / sum (machine_cpu_cores{node_role_kubernetes_io_infra=\"true\"}) * 100",
       "legendFormat": "Total Real Time CPU Usage on Infra"
      }
     ]
    },
    {
     "title": "Memory Allocation and Usage on Compute Nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (kube_resourcequota{resource=\"limits.memory\",type=\"hard\"}) / (sum (machine_memory_bytes{node_role_kubernetes_io_compute=\"true\"})) * 100 ",
       "legendFormat": "Total Memory Limits Allocated to Projects"
      },
      {
       "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"hard\"}) / (sum (machine_memory_bytes{node_role_kubernetes_io_compute=\"true\"})) * 100 ",
       "legendFormat": "Total Memory Requests Allocated to Projects"
      },
      {
       "expr": "(sum ((sum(kube_pod_container_resource_limits_memory_bytes{container!=\"deployment\",container!=\"docker-build\",namespace!=\"logging\",namespace!=\"default\",namespace!~\".*openshift-.*\",namespace!~\".*openmonitoring.*\",namespace!~\".*kube-.*\"}))*1000)) / (sum (machine_memory_bytes{node_role_kubernetes_io_compute=\"true\"})*1000)  * 100 ",
       "legendFormat": "Total Real Time Memory Limits Allocation"
      },
      {
       "expr": "(sum ((sum(kube_pod_container_resource_requests_memory_bytes{container!=\"deployment\",container!=\"docker-build\",namespace!=\"logging\",namespace!=\"default\",namespace!~\".*openshift-.*\",namespace!~\".*openmonitoring.*\",namespace!~\".*kube-.*\"}))*1000)) / (sum (machine_memory_bytes{node_role_kubernetes_io_compute=\"true\"})*1000)  * 100 ",
       "legendFormat": "Total Real Time Memory Request Allocation"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container!=\"\",name!~\"k8s_POD_.*\"}) / sum (machine_memory_bytes{node_role_kubernetes_io_compute=\"true\"}) * 100",
       "legendFormat": "Total Real Time Memory Usage on Compute"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container!=\"\",name!~\"k8s_POD_.*\"}}) / sum (machine_memory_bytes{node_role_kubernetes_io_master=\"true\"}) * 100",
       "legendFormat": "Total Real Time Memory Usage on Masters"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container!=\"\",name!~\"k8s_POD_.*\"}) / sum (machine_memory_bytes{node_role_kubernetes_io_infra=\"true\"}) * 100",
       "legendFormat": "Total Real Time Memory Usage on Infra"
      }
     ]
    },
    {
     "title": "Maximum Number of Pods we can Run on App Nodes",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 75 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(machine_cpu_cores{node_role_kubernetes_io_compute=\"true\"})*20"
      }
     ]
    },
    {
     "title": "Pod Limit",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1/((sum(machine_cpu_cores{node_role_kubernetes_io_compute=\"true\"})*20) / (sum (kube_pod_info{namespace!=\"default\",namespace!=\"openshift-infra\",namespace!=\"openshift-monitoring\",namespace!=\"logging\",created_by_kind!=\"<none>\"})))  * 100 "
      }
     ]
    },
    {
     "title": "Pods per Node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum (kube_pod_info) by (node) ", "legendFormat": "{{ node }}" }
     ]
    },
    {
     "title": "Current number of Running Pods",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 77 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (kube_pod_info{namespace!=\"default\",namespace!=\"openshift-infra\",namespace!=\"openshift-monitoring\",namespace!=\"logging\",created_by_kind!=\"<none>\"})"
      }
     ]
    },
    {
     "title": "Pods per Core",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 79 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "20" }
     ]
    },
    {
     "title": "Total Allocatable CPU cores on Compute Nodes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 81 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(machine_cpu_cores{node_role_kubernetes_io_compute=\"true\"})"
      }
     ]
    },
    {
     "title": "Total CPU Requests by Available Compute Cores",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"requests.cpu\",type=\"hard\"}) / sum(machine_cpu_cores{node_role_kubernetes_io_compute=\"true\"}) * 100"
      }
     ]
    },
    {
     "title": "Top 10 CPU Requests per Project",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "short", "label": "cpu cores" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(kube_resourcequota{resource=\"requests.cpu\",type=\"hard\"}) by (namespace))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Total CPU Request cores Assigned to Projects",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 84 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"requests.cpu\",type=\"hard\"})"
      }
     ]
    },
    {
     "title": "Total Allocatable CPU cores on Compute Nodes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 87 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(machine_cpu_cores{node_role_kubernetes_io_compute=\"true\"})"
      }
     ]
    },
    {
     "title": "Total CPU Limits by Available Compute Cores",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\"}) / sum(machine_cpu_cores{node_role_kubernetes_io_compute=\"true\"}) * 100"
      }
     ]
    },
    {
     "title": "Top 10 CPU Limits per Project",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 87 },
     "yaxes": [
      { "format": "short", "label": "cpu cores" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\"}) by (namespace))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Total CPU Limit cores Assigned to Projects",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 90 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.cpu\",type=\"hard\"})"
      }
     ]
    },
    {
     "title": "Total Allocatable Memory on Compute Nodes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 93 },
     "format": "bits",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(machine_memory_bytes{node_role_kubernetes_io_compute=\"true\"})"
      }
     ]
    },
    {
     "title": "Total Memory Resource Request by Available Memory",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"requests.memory\",type=\"hard\"}) / sum(machine_memory_bytes{node_role_kubernetes_io_compute=\"true\"}) *100"
      }
     ]
    },
    {
     "title": "Memory Request per Project",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 93 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "topk(10 ,sum(kube_resourcequota{resource=\"requests.memory\",type=\"hard\"}) by (namespace))",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Total Memory Request Allocated for all Projects",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 96 },
     "format": "bits",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"requests.memory\",type=\"hard\"})"
      }
     ]
    },
    {
     "title": "Total Allocatable Memory on Compute Nodes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 99 },
     "format": "bits",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(machine_memory_bytes{node_role_kubernetes_io_compute=\"true\"})"
      }
     ]
    },
    {
     "title": "Total Memory Resource Limits by Available Memory",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.memory\",type=\"hard\"}) / sum(machine_memory_bytes{node_role_kubernetes_io_compute=\"true\"}) *100"
      }
     ]
    },
    {
     "title": "Memory Limits per Project",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 99 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.memory\",type=\"hard\"}) by (namespace)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Total Memory Limits Allocated for all Projects",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 102 },
     "format": "bits",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_resourcequota{resource=\"limits.memory\",type=\"hard\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Vital Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Project Quotas - Memory Requests & Limits",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"used\"}) by (namespace)",
       "legendFormat": "{{ namespace }} (used)"
      },
      {
       "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"hard\"}) by (namespace)",
       "legendFormat": "{{ namespace }} (requests)"
      },
      {
       "expr": "sum (kube_resourcequota{resource=\"limits.memory\",type=\"hard\"}) by (namespace)",
       "legendFormat": "{{ namespace }} (limit)"
      },
      {
       "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"hard\"})",
       "legendFormat": "Total Requests"
      },
      {
       "expr": "sum (kube_resourcequota{resource=\"limits.memory\",type=\"hard\"})",
       "legendFormat": "Total Limits"
      },
      {
       "expr": "sum (machine_memory_bytes{role=\"app\"})",
       "legendFormat": "Total Memory"
      }
     ]
    },
    {
     "title": "Number of Block Device per Node",
     "type": "graph",
     "description": "VMware has a limit  of 64 block devices it can attach to a VM. This metric is important because Kubernetes can schedule a pod onto a node that cannot attach any more disk.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "none", "label": "number of disks attached" }
     ],
     "targets": [
      {
       "expr": "count(node_disk_io_now{device=~\"sd.*\"})  by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Pod Phase across Cluster",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase) by (phase)",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Project Quotas - CPU Requests & Limits",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\"}) by (namespace)",
       "legendFormat": "{{ namespace }} (used)"
      },
      {
       "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"hard\"}) by (namespace)",
       "legendFormat": "{{ namespace }} (requests)"
      },
      {
       "expr": "sum (kube_resourcequota{resource=\"limits.cpu\",type=\"hard\"}) by (namespace)",
       "legendFormat": "{{ namespace }} (limit)"
      },
      {
       "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"hard\"})",
       "legendFormat": "Total Requests"
      },
      {
       "expr": "sum (kube_resourcequota{resource=\"limits.cpu\",type=\"hard\"})",
       "legendFormat": "Total Limits"
      },
      {
       "expr": "sum (machine_cpu_cores{role=\"app\"})",
       "legendFormat": "Total Cores"
      }
     ]
    },
    {
     "title": "Disk Read/Write Throughput > 1MB/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total[2m]) ",
       "legendFormat": "{{ kubernetes_node }} - {{device}} - Bytes read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total[2m]) ",
       "legendFormat": "{{ kubernetes_node }} -  {{device}} - Bytes written"
      }
     ]
    },
    {
     "title": "HTTP Checks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      { "expr": "probe_http_status_code", "legendFormat": "{{ kubernetes_node }}" }
     ]
    }
   ]
  },
  {
   "title": "Network Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic Received > 100kpps",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 132 },
     "yaxes": [
      { "format": "pps", "label": "Traffic Received" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total[5m]) > 100000",
       "legendFormat": "{{ kubernetes_node }} - {{ device }}"
      }
     ]
    },
    {
     "title": "Network Traffic Transmitted > 100kpps",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 137 },
     "yaxes": [
      { "format": "pps", "label": "Traffic Transmitted" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_transmit_bytes_total[5m]) > 100000",
       "legendFormat": "{{ kubernetes_node }} - {{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Uptime",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 143 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "node_time_seconds - node_boot_time_seconds",
       "legendFormat": "{{ kubernetes_node }}"
      }
     ]
    },
    {
     "title": "Nodes Marked as Unscheduled",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 143 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_node_spec_unschedulable > 0",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Nodes Not Ready",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 149 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_node_status_condition{condition=\"Ready\",status=\"false\"} > 0",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Nodes with Disk Pressure",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 149 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"} > 0",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Nodes with Memory Pressure",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 155 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"} > 0",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Nodes with Out of Disk",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 155 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_node_status_condition{condition=\"OutOfDisk\",status=\"true\"} > 0",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Restarts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 169 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total > 0",
       "legendFormat": "{{ namespace }} | {{ pod }}"
      }
     ]
    },
    {
     "title": "Pods Stuck in Pending Phase",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 176 },
     "yaxes": [
      { "format": "s", "label": "time" }
     ],
     "targets": [
      {
       "expr": "time() - (kube_pod_start_time * on(pod, namespace) (kube_pod_status_phase{phase=\"Pending\"} == 1))",
       "legendFormat": "{{ namespace }} - {{ pod }}"
      },
      {
       "expr": "time() - (kube_pod_start_time * on(pod, namespace) (kube_pod_status_phase{phase!=\"Running\",phase!=\"Succeeded\",pod!~\".*-deploy.*\",pod!~\".*-build.*\"} == 1))",
       "legendFormat": "{{ namespace }} - {{ pod }}"
      }
     ]
    },
    {
     "title": "Pods per Node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 182 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum (kube_pod_info) by (node)", "legendFormat": "{{ node }}" }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape Duration",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 190 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(5, max(scrape_duration_seconds) by (job))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Kubernetes Information",
     "type": "table-old",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 200 },
     "targets": [
      { "expr": "kube_node_info" }
     ]
    }
   ]
  }
 ]
}