{
 "title": "Namespace Details",
 "description": "Displays Namespace utilization",
 "tags": [
  "kubernetes",
  "lsd-observe"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n<p style=\"text-align:center;\">LSDobserve - Kubernetes Namespace Details - Version 2.20</p>",
   "targets": [
    {}
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU Core Request Quota",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"requests.cpu\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "CPU Core Request Quota Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"requests.cpu\",type=\"used\"})"
    }
   ]
  },
  {
   "title": "CPU Core Limit Quota",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"limits.cpu\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "CPU Core Limit Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"limits.cpu\",type=\"used\"})"
    }
   ]
  },
  {
   "title": "RAM Requests Quota",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"requests.memory\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "RAM Requests Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"requests.memory\",type=\"used\"})"
    }
   ]
  },
  {
   "title": "RAM Limits Quota",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"limits.memory\",type=\"hard\"})"
    }
   ]
  },
  {
   "title": "RAM Requests Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"limits.memory\",type=\"used\"})"
    }
   ]
  },
  {
   "title": "Real Time CPU Requests for $Namespace",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"requests.cpu\",type=\"used\"}) / sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"requests.cpu\",type=\"hard\"}) * 100"
    }
   ]
  },
  {
   "title": "Real Time CPU Limits for $Namespace",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"limits.cpu\",type=\"used\"}) / sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"limits.cpu\",type=\"hard\"}) * 100"
    }
   ]
  },
  {
   "title": "Real Time Memory Requests for $Namespace",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"requests.memory\",type=\"used\"}) / sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"requests.memory\",type=\"hard\"}) * 100"
    }
   ]
  },
  {
   "title": "Real Time Memory Limits for $Namespace",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"limits.memory\",type=\"used\"}) / sum(kube_resourcequota{namespace=\"$Namespace\",resource=\"limits.memory\",type=\"hard\"}) * 100"
    }
   ]
  },
  {
   "title": "Total Network I/O pressure for  $Namespace",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{namespace=~\"^$Namespace$\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{namespace=~\"^$Namespace$\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Project $Namespace Quotas - CPU Requests & Limits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Millicores" }
   ],
   "targets": [
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"used\",namespace=~\"^$Namespace$\"}) * 1000",
     "legendFormat": "{{ $Namespace }} (used)"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.cpu\",type=\"hard\",namespace=~\"^$Namespace$\"}) * 1000",
     "legendFormat": "{{ $Namespace }} (requests)"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"limits.cpu\",type=\"hard\",namespace=~\"^$Namespace$\"}) * 1000",
     "legendFormat": "{{ $Namespace }} (limit)"
    }
   ]
  },
  {
   "title": "Project $Namespace Quotas - Memory Requests & Limits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"used\",namespace=~\"^$Namespace$\"}) ",
     "legendFormat": "{{ $Namespace }} (used)"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"requests.memory\",type=\"hard\",namespace=~\"^$Namespace$\"}) ",
     "legendFormat": "{{ $Namespace  }} (requests)"
    },
    {
     "expr": "sum (kube_resourcequota{resource=\"limits.memory\",type=\"hard\",namespace=~\"^$Namespace$\"}) ",
     "legendFormat": "{{ $Namespace }} (limit)"
    }
   ]
  },
  {
   "title": "Pods CPU usage for $Namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m]))",
     "legendFormat": "Total CPU Real Time Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"^$Namespace$\"} > 0)",
     "legendFormat": "Total CPU Real Time Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"^$Namespace$\"} > 0)",
     "legendFormat": "Total CPU Real Time Limits"
    }
   ]
  },
  {
   "title": "Total Pods memory usage for $Namespace",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes", "label": "Memory " }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"})",
     "legendFormat": "Total Memory Real Time Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"^$Namespace$\"} > 0)",
     "legendFormat": "Total Memory Real Time Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"^$Namespace$\"} > 0)",
     "legendFormat": "Total Memory Real Time Limits"
    }
   ]
  },
  {
   "title": "CPU request/usage disparity",
   "type": "graph",
   "description": "This displays the CPU requests vs actual CPUusage. For example if you see 5 cores here, that means this project is request 5 cores more than it requires.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"^$Namespace$\"}) - sum(rate(container_cpu_usage_seconds_total{namespace=~\"^$Namespace$\",image!=\"\",name=~\"^k8s_.*\"}[2m]))",
     "legendFormat": "$Namespace - CPU disparity"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"^$Namespace$\",image!=\"\",name=~\"^k8s_.*\"}[2m]))",
     "legendFormat": "$Namespace - CPU actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"^$Namespace$\"})",
     "legendFormat": "$Namespace - CPU requests"
    }
   ]
  },
  {
   "title": "Memory request/usage disparity",
   "type": "graph",
   "description": "This displays the memory requests vs actual usage. For example if you see 5GiB here, that means this project is request 5GiB more than it requires.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"^$Namespace$\"}) - sum(container_memory_working_set_bytes{namespace=~\"^$Namespace$\",image!=\"\",name=~\"^k8s_.*\"})",
     "legendFormat": "$Namespace - Memory disparity"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"^$Namespace$\",image!=\"\",name=~\"^k8s_.*\"})",
     "legendFormat": "$Namespace - Memory actual usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"^$Namespace$\"})",
     "legendFormat": "$Namespace - Memory requests"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "Number of Restarts" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"^$Namespace$\"} > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Total time duration the container has been throttled",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "time in seconds" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod!=\"\",namespace=\"$Namespace\"}[2m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Resource CPU Requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=~\"^$Namespace$\"} > 0",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pod CPU Limits",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=~\"^$Namespace$\"} > 0",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pods CPU usage (2m avg)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Containers CPU usage (2m avg)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",namespace=~\"^$Namespace$\"}[2m])) by (container_name, pod)",
       "legendFormat": "pod: {{ pod }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (fqdn, name, image)",
       "legendFormat": "docker: {{ fqdn }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",namespace=~\"^$Namespace$\"}[2m])) by (fqdn, rkt_container_name)",
       "legendFormat": "rkt: {{ fqdn }} | {{ rkt_container_name }}"
      }
     ]
    },
    {
     "title": "Right Sizing Table",
     "type": "table",
     "description": "Table to help you decide the correct requests and limits to set on a deployment",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"^$Namespace$\"}) by (pod) *1000"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"^$Namespace$\"}) by (pod) *1000"
      },
      {
       "expr": "label_replace (sum by(pod) (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"invest-qa\"}[2m])), \"pod\", \"$1\", \"pod\", \"(.+)\") *1000"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Memory Requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "bytes", "label": "Memory " }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=~\"^$Namespace$\"} > 0",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pods Memory Limits",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "bytes", "label": "Memory " }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=~\"^$Namespace$\"} > 0",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",namespace=~\"^$Namespace$\"}) by (container_name, pod)",
       "legendFormat": "pod: {{ pod }} | {{ container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",namespace=~\"^$Namespace$\"}) by (fqdn, name, image)",
       "legendFormat": "docker: {{ fqdn }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",namespace=~\"^$Namespace$\"}) by (fqdn, rkt_container_name)",
       "legendFormat": "rkt: {{ fqdn }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods network I/O (2m avg)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (pod)",
       "legendFormat": "-> {{ pod }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (pod)",
       "legendFormat": "<- {{ pod }}"
      }
     ]
    },
    {
     "title": "Containers network I/O (2m avg)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (container_name, pod)",
       "legendFormat": "-> pod: {{ pod }} | {{ container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (container_name, pod)",
       "legendFormat": "<- pod: {{ pod }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (fqdn, name, image)",
       "legendFormat": "-> docker: {{ fqdn }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",namespace=~\"^$Namespace$\"}[2m])) by (fqdn, name, image)",
       "legendFormat": "<- docker: {{ fqdn }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",namespace=~\"^$Namespace$\"}[2m])) by (fqdn, rkt_container_name)",
       "legendFormat": "-> rkt: {{ fqdn }} | {{ rkt_container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",namespace=~\"^$Namespace$\"}[2m])) by (fqdn, rkt_container_name)",
       "legendFormat": "<- rkt: {{ fqdn }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  }
 ]
}