# Logstash ConfigMaps
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
data:
  logstash.conf: |-
{{ .Files.Get "logstash/pipeline-logstash.conf" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-lsdobserve
data:
  001-pipeline.conf: |-
{{ .Files.Get "logstash/pipeline-lsdobserve.conf" | indent 4}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-patterns
data:
  lsdobserve-basic: |-
{{ .Files.Get "logstash/patterns-lsdobserve-basic" | indent 4}}
  lsdobserve-utility: |-
{{ .Files.Get "logstash/patterns-lsdobserve-utility" | indent 4}}
---
