{{- if .Values.lsdobserve.resourceQuota.enabled -}}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Name }}
spec:
  hard:
    requests.cpu: "6"
    limits.cpu: "20"
    requests.memory: "32Gi"
    limits.memory: "60Gi"
    requests.storage: "1Ti"
    persistentvolumeclaims: "20"
    requests.nvidia.com/gpu: 4
    configmaps: "50"
    pods: "100"
    replicationcontrollers: "50"
    secrets: "100"
    services: "100"
    services.loadbalancers: "10"
{{- end }}
{{- if .Values.lsdobserve.limitRange.enabled -}}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Name }}
spec:
  limits:
  - max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 10m
      memory: 4Mi
    type: Pod
  - default:
      cpu: 400m
      memory: 512Mi
    defaultRequest:
      cpu: 200m
      memory: 128Mi
    max:
      cpu: "4"
      memory: 8Gi
    maxLimitRequestRatio:
      cpu: "20"
    min:
      cpu: 10m
      memory: 4Mi
    type: Container
{{- end }}
