# Grafana Configmap

# Grafana Ingress
{{- if or (eq .Values.lsdmop.clusterType "gke") (eq .Values.lsdmop.clusterType "rancher") -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"    
  name: lsdmop-grafana
spec:
  rules:
  - host: {{ .Values.lsdmop.grafana.ingress.url }}
    http:
      paths:
      - backend:
          service:
            name: lsdmop-grafana
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
---
{{- end }}

# Grafana Route for Openshift
{{- if eq .Values.lsdmop.clusterType "openshift" -}}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Release.Name }}-grafana
  name: {{ .Release.Name }}-grafana
spec:
  host: {{ .Values.lsdmop.grafana.ingress.url }}
  port:
    targetPort: service
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Release.Name }}-grafana
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted
    host: {{ .Values.lsdmop.grafana.ingress.url }}
    routerName: router
    wildcardPolicy: None
---
{{- end }}
