{
 "title": "Rook Ceph",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "kubernetes",
  "lsdcontainer",
  "ceph",
  "rook"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "cluster", "label": "cluster", "query": "label_values(rook_cluster)" }
  ]
 },
 "panels": [
  { "title": "Cluster State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_health_status{rook_cluster=\"$cluster\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_w_in_bytes{rook_cluster=\"$cluster\"}[2m]))"
    }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (ceph_daemon, instance) (irate(ceph_osd_op_r_out_bytes{rook_cluster=\"$cluster\"}[2m]))"
    }
   ]
  },
  {
   "title": "Cluster Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_cluster_total_bytes{rook_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Available Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (sum without(instance) ((ceph_cluster_total_bytes - ceph_cluster_total_used_bytes) / ceph_cluster_total_bytes) * 100)"
    }
   ]
  },
  {
   "title": "Mon Session Num",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_mon_num_sessions{rook_cluster='$cluster'})"
    }
   ]
  },
  {
   "title": "Monitors In Quorum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without (instance, ceph_daemon) (ceph_mon_quorum_status{rook_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{rook_cluster='$cluster',alertstate='firing',alertname=~'^CephCluster.*'}) OR vector(0)"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (ceph_daemon, instance) (irate(ceph_osd_op_w{rook_cluster=\"$cluster\"}[2m]))"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (ceph_daemon, instance) (irate(ceph_osd_op_r{rook_cluster=\"$cluster\"}[2m]))"
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance) (ceph_cluster_total_used_bytes{rook_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, pool_id) (ceph_pool_objects{rook_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_op_w_in_bytes{rook_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_op_r_out_bytes{rook_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "OSDs OUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without (instance, ceph_daemon) (ceph_osd_up{rook_cluster=\"$cluster\"}) - count without (instance, ceph_daemon) (ceph_osd_in{rook_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ceph_osd_up{rook_cluster=\"$cluster\"} == 0.0) OR vector(0)"
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_up{rook_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, ceph_daemon) (ceph_osd_in{rook_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Avg PGs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (ceph_osd_numpg{rook_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Avg Apply Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (ceph_osd_apply_latency_ms{rook_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Avg Commit Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ceph_osd_commit_latency_ms{rook_cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Avg Op Write Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_w_latency_sum{rook_cluster=\"$cluster\"}[2m]) / rate(ceph_osd_op_w_latency_count{rook_cluster=\"$cluster\"}[2m]) >= 0)"
    }
   ]
  },
  {
   "title": "Avg  Op Read Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_r_latency_sum{rook_cluster=\"$cluster\"}[2m])/rate(ceph_osd_op_r_latency_count{rook_cluster=\"$cluster\"}[2m]) >= 0)"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum without (instance) (ceph_cluster_total_bytes{rook_cluster=\"$cluster\"})",
       "legendFormat": "Total Capacity"
      },
      {
       "expr": "sum without (instance) (ceph_cluster_total_bytes{rook_cluster=\"$cluster\"}-ceph_cluster_total_used_bytes{rook_cluster=\"$cluster\"})",
       "legendFormat": "Available"
      },
      {
       "expr": "sum without (instance) (ceph_cluster_total_used_bytes{rook_cluster=\"$cluster\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_w_in_bytes{rook_cluster=\"$cluster\"}[2m]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_r_out_bytes{rook_cluster=\"$cluster\"}[2m]))",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Pool Bytes Recovered",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum((ceph_pool_num_bytes_recovered{rook_cluster='$cluster'}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{rook_cluster='$cluster'})) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_w{rook_cluster=\"$cluster\"}[2m]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_r{rook_cluster=\"$cluster\"}[2m]))",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Pool Quota Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum without (instance) ((ceph_pool_quota_bytes{rook_cluster='$cluster'}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{rook_cluster='$cluster'}))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Objects Per Pool",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance) ((ceph_pool_objects{rook_cluster='$cluster'}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{rook_cluster='$cluster'}))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pool Objects Recovered",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, pool_id) ((ceph_pool_num_objects_recovered{rook_cluster='$cluster'}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{rook_cluster='$cluster'}))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "OSD Type Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count without (instance, ceph_daemon) (ceph_bluestore_commit_lat_count{rook_cluster='$cluster'})",
       "legendFormat": "BlueStore"
      },
      {
       "expr": "count without (instance, ceph_daemon) (ceph_filestore_journal_latency_count{rook_cluster='$cluster'})",
       "legendFormat": "FileStore"
      }
     ]
    },
    {
     "title": "Pool Objects Quota",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance) (ceph_pool_quota_objects{rook_cluster='$cluster'}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{rook_cluster='$cluster'})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSD Apply Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "ceph_osd_apply_latency_ms{rook_cluster='$cluster'}"
      }
     ]
    },
    {
     "title": "OSD Commit Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "ceph_osd_commit_latency_ms{rook_cluster='$cluster'}"
      }
     ]
    },
    {
     "title": "OSD Read Op Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_r_latency_sum{rook_cluster=\"$cluster\"}[2m]) / rate(ceph_osd_op_r_latency_count{rook_cluster=\"$cluster\"}[2m]) >= 0"
      }
     ]
    },
    {
     "title": "OSD Write Op Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_w_latency_sum{rook_cluster=\"$cluster\"}[2m]) / rate(ceph_osd_op_w_latency_count{rook_cluster=\"$cluster\"}[2m]) >= 0"
      }
     ]
    },
    {
     "title": "Avg OSD  Op  Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg without (instance,ceph_daemon) (rate(ceph_osd_op_r_latency_sum{rook_cluster=\"$cluster\"}[2m]) / rate(ceph_osd_op_r_latency_count{rook_cluster=\"$cluster\"}[2m]) >= 0)",
       "legendFormat": "read"
      },
      {
       "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_w_latency_sum{rook_cluster=\"$cluster\"}[2m]) / rate(ceph_osd_op_w_latency_count{rook_cluster=\"$cluster\"}[2m]) >= 0)",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "AVG OSD Apply + Commit Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg without (instance, ceph_daemon) (ceph_osd_apply_latency_ms{rook_cluster=\"$cluster\"})",
       "legendFormat": "apply"
      },
      {
       "expr": "avg without (instance, ceph_daemon) (ceph_osd_commit_latency_ms{rook_cluster=\"$cluster\"})",
       "legendFormat": "commit"
      }
     ]
    }
   ]
  },
  {
   "title": "Objects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Objects in the Cluster",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, pool_id) (ceph_pool_objects)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "PGs State",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_active{rook_cluster=\"$cluster\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_clean{rook_cluster=\"$cluster\"})",
       "legendFormat": "Clean"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_peering{rook_cluster=\"$cluster\"})",
       "legendFormat": "Peering"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_degraded{rook_cluster=\"$cluster\"})",
       "legendFormat": "Degraded"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_stale{rook_cluster=\"$cluster\"})",
       "legendFormat": "Stale"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_unclean_pgs{rook_cluster=\"$cluster\"})",
       "legendFormat": "Unclean"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_undersized{rook_cluster=\"$cluster\"})",
       "legendFormat": "Undersized"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_incomplete{rook_cluster=\"$cluster\"})",
       "legendFormat": "Incomplete"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_forced_backfill{rook_cluster=\"$cluster\"})",
       "legendFormat": "Forced Backfill"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_inconsistent{rook_cluster=\"$cluster\"})",
       "legendFormat": "Inconsistent"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_forced_recovery{rook_cluster=\"$cluster\"})",
       "legendFormat": "Forced Recovery"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_creating{rook_cluster=\"$cluster\"})",
       "legendFormat": "Creating"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_wait_backfill{rook_cluster=\"$cluster\"})",
       "legendFormat": "Wait Backfill"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_deep{rook_cluster=\"$cluster\"})",
       "legendFormat": "Deep"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_scrubbing{rook_cluster=\"$cluster\"})",
       "legendFormat": "Scrubbing"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_recovering{rook_cluster=\"$cluster\"})",
       "legendFormat": "Recovering"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_repair{rook_cluster=\"$cluster\"})",
       "legendFormat": "Repair"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_down{rook_cluster=\"$cluster\"})",
       "legendFormat": "Down"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_peered{rook_cluster=\"$cluster\"})",
       "legendFormat": "Peered"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_backfill{rook_cluster=\"$cluster\"})",
       "legendFormat": "Backfill"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_remapped{rook_cluster=\"$cluster\"})",
       "legendFormat": "Remapped"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_backfill_toofull{rook_cluster=\"$cluster\"})",
       "legendFormat": "Backfill Toofull"
      }
     ]
    },
    {
     "title": "Stuck PGs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_degraded{rook_cluster=\"$cluster\"})",
       "legendFormat": "Degraded"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_stale{rook_cluster=\"$cluster\"})",
       "legendFormat": "Stale"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_undersized{rook_cluster=\"$cluster\"})",
       "legendFormat": "Undersized"
      }
     ]
    },
    {
     "title": "Recovery Operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_recovery_ops{rook_cluster=\"$cluster\"}[$__rate_interval]))",
       "legendFormat": "OPS"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts from CephThanos",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "ALERTS{rook_cluster='$cluster', alertstate='firing'}"
      }
     ]
    },
    {
     "title": "Top Sluggish OSD's",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
     "targets": [
      {
       "expr": "topk(5,sort_desc(ceph_osd_apply_latency_ms{rook_cluster='$cluster'} + ceph_osd_commit_latency_ms{rook_cluster='$cluster'}))"
      }
     ]
    },
    {
     "title": "Down OSD's",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
     "targets": [
      {
       "expr": "{rook_cluster=\"$cluster\"} == 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ceph OSD Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (ceph_version) (ceph_osd_metadata{rook_cluster='$cluster'})",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    },
    {
     "title": "Ceph Mon Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_mon_metadata{rook_cluster='$cluster'})",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    },
    {
     "title": "Ceph MDS Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_mds_metadata{rook_cluster='$cluster'})",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    },
    {
     "title": "Ceph RGW Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_rgw_metadata{rook_cluster='$cluster'})",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    }
   ]
  }
 ]
}