{
 "title": "Node & Namespace Details",
 "description": "Monitors Kubernetes clusters using Prometheus. Shows Namespace/Node level CPU Cores / Memory / Network IO and PVC usage of both aggregate pod sets and individual pods.",
 "tags": [
  "kubernetes",
  "lsd-observe"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   { "name": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\n<p style=\"text-align:center;\">LSD Observe - Node & Namespace Details - Version 2.27</p>",
   "targets": [
    {}
   ]
  },
  { "title": "TOP 5", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Top Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}) by (pod,namespace,instance))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Top Pod MB/s Write",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(irate(container_fs_writes_total{pod!~\"rook-ceph-osd.*|glusterfs-storage.*\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}[2m])) by (pod,namespace,instance)) > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods CPU usage ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(irate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\",kubernetes_io_hostname=~\"^$Node$\"}[2m])) by (pod))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Top Memory Request",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(kube_pod_container_resource_requests_memory_bytes{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}) by (pod,namespace))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Top Pod MB/s Read",
   "type": "graph",
   "description": "Instant top5k over range seems to give a rough average over a certain time period - without instant rouge values appear. Compare with non-instant graph averages. Close enough.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(irate(container_fs_reads_total{pod!~\"rook-ceph-osd.*|glusterfs-storage.*\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}[2m])) by (pod,namespace,instance)) > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Top CPU Request",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(kube_pod_container_resource_requests_cpu_cores{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}) by (pod,namespace))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Top 5 Largest Memory request/usage disparity per namespace",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, (sum(kube_pod_container_resource_requests_memory_bytes{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}) by (namespace)) - (sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}) by (namespace)))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Top 5 Largest CPU request/usage disparity per namespace",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5, (sum(kube_pod_container_resource_requests_cpu_cores{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}) by (namespace)) - (sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}[2m])) by (namespace)))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod MB/s Read",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_reads_total{pod!~\"rook-ceph-osd.*\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}[2m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pod MB/s Write",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_total{pod!~\"rook-ceph-osd.*|glusterfs-storage.*\",image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"^$Namespace$\"}[2m])) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O pressure",
     "type": "graph",
     "description": "Physical network I/O pressure",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}[2m])) * 8",
       "legendFormat": "<-- RX"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}[2m])) * 8",
       "legendFormat": "--> TX"
      }
     ]
    },
    {
     "title": "Pod Network RX/TX > 0",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}[2m]) * 8 > 0 ",
       "legendFormat": "<- {{ pod }}"
      },
      {
       "expr": "- rate(container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}[2m]) * 8 < 0",
       "legendFormat": "-> {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods CPU usage ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sort_desc(sum (irate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}[2m])) by (pod))",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pod sets CPU usage",
     "type": "graph",
     "description": "Aggregate of all pod(s) in a specific set, e.g. statefulset.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (irate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace\"}[2m])) by (container_name,pod)",
       "legendFormat": "{{ container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pod sets memory usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}) by (container_name)",
       "legendFormat": "{{ container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}) by (kubernetes_io_hostname, name, image)",
       "legendFormat": "({{ name }})"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace$\"}) by (kubernetes_io_hostname, rkt_container_name)",
       "legendFormat": "rkt: {{ kubernetes_io_hostname }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "PVC space available",
     "type": "graph",
     "description": "Enabled per storage plugin:\n- https://github.com/rook/rook/issues/1659\n- https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/3.11/html/operations_guide/enable_vol_metrics",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_available_bytes{kubernetes_io_hostname=~\"^$Node$\",namespace=~\"^$Namespace\"}",
       "legendFormat": "{{ persistentvolumeclaim }}"
      }
     ]
    }
   ]
  }
 ]
}