{
 "title": "LSDautomate Overview",
 "description": "LSDautomate Overview",
 "tags": [
  "Prometheus",
  "blackbox_exporter",
  "lsdautomate"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LSDautomate Vital Information",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "probe_success - 0" },
    { "expr": "probe_http_ssl - 0" },
    { "expr": "probe_http_status_code - 0" },
    {
     "expr": "probe_ssl_earliest_cert_expiry - time()"
    }
   ]
  },
  {
   "title": "LSDautomate Ingress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "probe_duration_seconds", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "HTTPS Probe Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "probe_http_duration_seconds", "legendFormat": "{{instance}} - {{phase}}" }
   ]
  },
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "rollback/commit",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(pg_stat_database_xact_rollback)/sum(pg_stat_database_xact_commit))*100"
    }
   ]
  },
  {
   "title": "PG buffer cache hit rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 21 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(100*sum(pg_stat_database_blks_hit) / (sum(pg_stat_database_blks_hit) + sum(pg_stat_database_blks_read)),0.1)",
     "legendFormat": "pg cache hit rate"
    }
   ]
  },
  {
   "title": "Sum ExclusiveLock on instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(pg_locks_count{datname!=\"postgres\", mode!=\"accesssharelock\", mode!=\"rowsharelock\", mode!=\"sharelock\"} > 1)",
     "legendFormat": "{{datname}} {{mode}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Count idle in transaction",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"idle in transaction\"})",
     "legendFormat": "idle in transaction sessions"
    }
   ]
  },
  {
   "title": "% current/total connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(pg_stat_activity_count) / sum(pg_settings_max_connections)) * 100",
     "legendFormat": "total/all connection"
    }
   ]
  },
  {
   "title": "Transactions per second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(pg_stat_database_xact_rollback[2m])) + sum(rate(pg_stat_database_xact_commit[2m])))/60",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Sum ShareLock on instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(pg_locks_count{datname!=\"postgres\", mode!=\"accessexclusivelock\", mode!=\"exclusivelock\", mode!=\"rowexclusivelock\", mode!=\"sharerowexclusivelock\", mode!=\"shareupdateexclusivelock\" })",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "singlestat",
   "description": "Connected sessions, including Postgres internal processes like Autovacuum. < 1 Warn / > 300 Error thresholds by default",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 23 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\"})"
    }
   ]
  },
  {
   "title": "Count general connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pg_settings_max_connections", "legendFormat": "max_connections" },
    { "expr": "sum(pg_stat_activity_count)", "legendFormat": "total connections" },
    {
     "expr": "sum(pg_stat_activity_count{state=\"idle\"})",
     "legendFormat": "idle sessions"
    },
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\"})",
     "legendFormat": "active sessions"
    },
    {
     "expr": "sum(pg_stat_activity_count{state=\"idle in transaction\"})",
     "legendFormat": "idle in transaction sessions"
    },
    {
     "expr": "sum(pg_stat_activity_count{state=\"idle in transaction (aborted)\"})",
     "legendFormat": "idle in transaction (aborted) sessions"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\"} !=0",
     "legendFormat": "{{datname}}, s: {{state}}"
    }
   ]
  },
  {
   "title": "Connections in detail",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, (pg_stat_activity_count))",
     "legendFormat": "{{datname}} {{state}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit / (pg_stat_database_blks_read + pg_stat_database_blks_hit)",
     "legendFormat": "{{datname}} Cache Hit Rate"
    }
   ]
  },
  {
   "title": "Longest Transaction",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration > 0",
     "legendFormat": "{{datname}} max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Read Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched[5m]) > 1000",
     "legendFormat": "{{datname}} SELECT (index scan)"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned[5m]) > 1000",
     "legendFormat": "{{datname}} SELECT (table scan)"
    }
   ]
  },
  {
   "title": "Change Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted[5m]) > 1",
     "legendFormat": "{{datname}} INSERT"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated[5m]) > 1",
     "legendFormat": "{{datname}} UPDATE"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted[5m]) > 1",
     "legendFormat": "{{datname}} DELETE"
    }
   ]
  },
  {
   "title": "PG buffer cache hit rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "round(100*sum(pg_stat_database_blks_hit) / (sum(pg_stat_database_blks_hit) + sum(pg_stat_database_blks_read)),0.1)",
     "legendFormat": "pg cache hit rate"
    }
   ]
  }
 ]
}