# LSDcontainer
lsdcontainer:
  # k8s-flavour options are: openshift, gke, rancher
  clusterType: gke
  minio:
    enabled: "true"
    image: "minio/minio:RELEASE.2021-08-05T22-01-19Z"
    accesskey: "admin"
    secretkey: "Ooyee3yieb7uv5Eiph1aithaik0ahjou"
    servers: 1
    volumesperserver: 4
    # volumesize is in Gi
    volumesize: 25
    storageclass: standard
    resources:
      requests:
        cpu: 25m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 2Gi
    console:
      image: minio/console:v0.9.4
      accesskey: "lsdcontainer"
      secretkey: "ooMee0evooghoo9yo8thai4oosilieph"
      # change the pbkdf to something random for both Passphrase and Salt
      pbkdfPassphrase: ohk3thood4Aiw4aiT9tohs1oucheifie
      pbkdfSalt: UOX3OFDpcVz3ZVbjHa233ymSpVfGJzz1
      ingress:
        annotations: {}
          ingress.kubernetes.io/ssl-redirect: "true"
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
          cert-manager.io/cluster-issuer: letsencrypt-staging
        hostname: lsdcontainer-minio-console.apps.cluster-01.gke.lsd.co.za
velero:
  image:
    repository: velero/velero
    tag: v1.6.3
    pullPolicy: IfNotPresent
    imagePullSecrets: []
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.2.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /target
      name: plugins
  metrics:
    enabled: true
    scrapeInterval: 30s
    scrapeTimeout: 10s
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8085"
      prometheus.io/path: "/metrics"
    serviceMonitor:
      enabled: false
      additionalLabels: {}
  kubectl:
    image:
      repository: docker.io/bitnami/kubectl
      tag: 1.16.15
  upgradeCRDs: true
  cleanUpCRDs: false
  configuration:
    provider: aws
    backupStorageLocation:
      name: default
      provider: aws
      bucket: velero
      caCert: {}
      prefix: {}
      default: {}
      config:
        region: minio
        s3ForcePathStyle: "true"
        s3Url: http://lsdcontainer-minio-hl:9000
  rbac:
    create: true
    clusterAdministrator: true
  serviceAccount:
    server:
      create: true
  credentials:
    useSecret: true
    name: velero-credentials
    existingSecret: {}
    secretContents:
      cloud: |
        [default]
        aws_access_key_id=lsdcontainer
        aws_secret_access_key=SuperDuperPassword
    extraEnvVars: {}
    extraSecretRef: ""
  backupsEnabled: true
  snapshotsEnabled: false
  deployRestic: false
  restic:
    podVolumePath: /var/lib/kubelet/pods
    privileged: false
    priorityClassName: ""
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1024Mi
