{{ if eq .Values.ahoy.clusterType "kubernetes" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: ahoy-server
  name: ahoy-server
spec:
  {{ if .Values.ahoy.tlsSecret }}
  tls:
    - secretName: {{ .Values.ahoy.tlsSecret }}
  {{ end }}
  rules:
    - host: {{ .Values.ahoy.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ahoy-server
                port:
                  number: 8080
  {{ end }}
